services:
  api:
    build:
      context: ./api-server
    ports:
      - "8000:8000"
    volumes:
      - api_db:/app/db.sqlite3

  ui:
    build:
      context: ./ui-client/product-dashboard-react
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api

volumes:
  api_db:

